# Generated by Django 5.0.2 on 2024-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=40)),
                ('movie_release_year', models.IntegerField()),
                ('movie_genre', models.CharField(max_length=40)),
                ('movie_director', models.CharField(max_length=40)),
                ('movie_protagonist', models.CharField(max_length=40)),
                ('movie_poster', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='new_movie_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_score', models.IntegerField()),
                ('favorite_movie_character', models.CharField(max_length=30)),
                ('movie_review', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='new_show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=40)),
                ('show_release_year', models.IntegerField()),
                ('show_director', models.CharField(max_length=40)),
                ('show_protagonist', models.CharField(max_length=40)),
                ('show_poster', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='new_show_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_score', models.IntegerField()),
                ('favorite_show_character', models.CharField(max_length=30)),
                ('show_review', models.CharField(max_length=250)),
            ],
        ),
    ]
