# Generated by Django 5.0.2 on 2024-03-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_critik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_show',
            name='show_genre',
            field=models.CharField(default='---', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new_movie',
            name='movie_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='new_movie',
            name='movie_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='new_show',
            name='show_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='new_show',
            name='show_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters'),
        ),
    ]
