# Generated by Django 5.0.2 on 2024-03-23 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_critik', '0003_new_movie_usuario_new_show_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_movie_review',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_critik.new_movie'),
        ),
        migrations.AddField(
            model_name='new_show_review',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_critik.new_show'),
        ),
    ]
