# Generated by Django 5.0.2 on 2024-03-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_critik', '0004_new_movie_review_comment_new_show_review_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_show_review',
            old_name='comment',
            new_name='show',
        ),
        migrations.AlterField(
            model_name='new_movie_review',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App_critik.new_movie'),
        ),
    ]
