# Generated by Django 5.0.2 on 2024-03-23 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_critik', '0005_rename_comment_new_show_review_show_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_movie_review',
            name='comment',
        ),
        migrations.AddField(
            model_name='new_movie_review',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_critik.new_movie'),
        ),
    ]
